name: tweet4minecraft
main: com.xsota.Tweet4minecraft
version: 0.0.0
author: xsota
website: https://github.com/xsota/tweet4minecraft

commands:
  selfharm:
    description: This is a self harm command.
    usage: /<command>
    permission: xsotaHardcore.basic    
    permission-message: You don\'t have <permission>

permissions:
  tweet4minecraft.*:
    description: Gives access to all commands
    children:
      xsotaHardcore.basic: true
  tweet4minecraft.basic:
    description: Gives access to basic commands
    default: true